#%RAML 1.0
title: Mycloudhub

/details:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "Sairam you are successfully completed your mulesoft training"
              }